[package]
name = "matrix-sdk-sql"
version = "0.1.0-beta.2"
edition = "2021"
authors = ["Charlotte 🦝 Delenk <lotte@chir.rs>"]
rust-version = "1.62.0"
description = "SQL-Based State Storage for matrix-sdk"
readme = "README.md"
repository = "https://github.com/DarkKirb/matrix-sdk-statestore-sql"
license = "Apache-2.0"
keywords = ["matrix", "sql"]
categories = ["database", "caching"]

[features]
default = ["native-tls", "postgres"]

native-tls = ["sqlx/runtime-tokio-native-tls"]
rustls = ["sqlx/runtime-tokio-rustls"]

postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

e2e-encryption = [
    "bincode",
    "dashmap",
    "educe",
    "matrix-sdk-base/e2e-encryption",
    "matrix-sdk-crypto",
    "matrix-sdk-store-encryption",
    "parking_lot",
    "serde",
    "vodozemac",
]

# Internal feature used by ci builds
ci = []

[dependencies]
async-trait = "0.1.53"
bincode = { version = "1.3.3", optional = true }
dashmap = { version = "5.2.0", optional = true }
futures = "0.3.21"
matrix-sdk-base = "0.6.1"
matrix-sdk-crypto = { version = "0.6.0", optional = true }
matrix-sdk-store-encryption = { version = "0.2.0", optional = true }
parking_lot = { version = "0.12.0", optional = true }
ruma = "0.7.4"
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = { version = "1.0.81" }
thiserror = "1.0.31"
vodozemac = { version = "0.3.0", optional = true }
tracing = "0.1.37"

[dependencies.educe]
version = "0.4.19"
default-features = false
features = ["Debug"]
optional = true

[dependencies.sqlx]
version = "0.6.0, <0.6.2"      # 0.6.2 is a breaking change
features = ["migrate", "json"]

[dependencies.sqlx-core]
version = "0.6.3"

[dev-dependencies.tokio]
version = "1.18.1"
features = ["macros", "rt-multi-thread"]
default-features = false

[dev-dependencies]
matrix-sdk-base = { version = "0.6.1", features = ["testing"] }
matrix-sdk-crypto = { version = "0.6.0", features = ["testing"] }
matrix-sdk-test = { version = "0.6.0" }
matrix-sdk-common = "0.6.0"
once_cell = "1.10.0"
tempfile = "3.3.0"
