[package]
name = "matrix-sdk-sql"
version = "0.1.0-beta.1"
edition = "2021"
authors = ["Charlotte 🦝 Delenk <lotte@chir.rs>"]
rust-version = "1.60.0"
description = "SQL-Based State Storage for matrix-sdk"
readme = "README.md"
repository = "https://github.com/DarkKirb/matrix-sdk-statestore-sql"
license = "Apache-2.0"
keywords = ["matrix", "sql"]
categories = ["database", "caching"]

[features]
default = ["native-tls", "postgres"]

native-tls = ["sqlx/runtime-tokio-native-tls"]
rustls = ["sqlx/runtime-tokio-rustls"]

postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

e2e-encryption = [
    "matrix-sdk-base/e2e-encryption",
    "matrix-sdk-store-encryption",
]

# Internal feature used by ci builds
ci = []

[dependencies]
async-trait = "0.1.53"
anyhow = "1.0.57"
futures = "0.3.21"
matrix-sdk-base = "0.5.0"
matrix-sdk-store-encryption = { version = "0.1.0", optional = true }
ruma = "0.6.2"

[dependencies.sqlx]
version = "0.5.13"
features = ["migrate", "json"]

[dev-dependencies.tokio]
version = "1.18.1"
features = ["macros", "rt-multi-thread"]
default-features = false

[dev-dependencies]
matrix-sdk-base = { version = "0.5.0", features = ["testing"] }
matrix-sdk-test = "0.5.0"
once_cell = "1.10.0"
tempfile = "3.3.0"
serde_json = "1.0.79"
